name: SpringBoot CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build Jar
        run: mvn clean package -DskipTests
        working-directory: SwaggerDemo


#      - name: Sonar Scan
#        run: mvn sonar:sonar \
#          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
#          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
#        working-directory: SwaggerDemo


      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/demoswagger:${{ github.sha }} .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/demoswagger:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop demoswagger || true
            docker rm demoswagger || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/demoswagger:latest
            docker run -d -p 8084:8084 --name demoswagger ${{ secrets.DOCKERHUB_USERNAME }}/demoswagger:latest